[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"

# ✅ Configurações para SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Cache otimizado para assets
[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"
    "X-Content-Type-Options" = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

# ✅ Otimização para Yarn
[build.settings]
  command = "yarn build"